---
version: '2'
linters:
  default: none
  enable: [coverlint]
  settings:
    custom:
      coverlint:
        type: module
        settings:
          rules:
            - pattern: '**'
              min: 0.80
            - pattern: '**/*_test'
              min: 0.0
